//GET http://localhost:3001/api/persons/

###

//title: String,
//author: String,
//url: String,
//likes: Number

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blue World", 
    "author": "All day",
    "url": "inside/outside",
    "likes": 1998
}