//GET http://localhost:3001/api/persons/

###

//title: String,
//author: String,
//url: String,
//likes: Number

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Bow",
    "name": "Pappy",
    "password": "reaction"
}